name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nawazish.hashnode.dev/rss.xml"
          max_post_count: 5